--CREATE VIEW [SD_items_by_vendor_UPC] AS

SELECT DISTINCT

	 i.ITEMID,
	i.NAMEALIAS,
	i.PrimaryVendorId,
	v.NAME AS 'Vendor Name',
	c.EXTERNALITEMID AS 'ExternalID',
	b.ITEMBARCODE AS 'BarCode',
	b.BARCODESETUPID,
	i.ITEMBUYERGROUPID AS 'Buyer',
	i.LHAPARENTSKU AS 'ParentSKU',
	REPLACE(REPLACE(REPLACE(i.OSSEXSTOCKFLAG,'1','Ex-stock'),'2','Ex-stock and Due In'),'0','None') AS 'Ex-stock',
	i.CITREQITEMWHSEID AS 'ManualCoverage',
	i.LHAMERCHDISCONID AS 'Discontinued',
	SUM(s.AVAILPHYSICAL) AS 'InventoryAvailable',
	SUM(s.ONORDER) AS 'BackOrdered'

FROM InventTable i

LEFT JOIN CustVendExternalItem c ON i.ITEMID = c.ITEMID AND i.PrimaryVendorId = c.CustVendRelation

LEFT JOIN InventSum s ON i.ITEMID = s.ITEMID

JOIN Vendor v ON i.PRIMARYVENDORID = v.ACCOUNTNUM

JOIN InventItemBarCode b ON i.ITEMID = b.ITEMID

WHERE c.MODULETYPE = '3' AND (b.BARCODESETUPID = 'ISBN' or b.BARCODESETUPID = 'UPCA') 

GROUP BY i.ITEMID, i.NAMEALIAS, i.PRIMARYVENDORID, v.NAME, c.EXTERNALITEMID, b.ITEMBARCODE, i.ITEMBUYERGROUPID, i.LHAPARENTSKU, i.OSSEXSTOCKFLAG, i.CITREQITEMWHSEID, i.LHAMERCHDISCONID, b.BARCODESETUPID

--ORDER BY i.ITEMID