--CREATE VIEW [SD_LANDED_COST] AS

SELECT

		t.ITEMID,
		t.QTY,
		t.INVENTDIMID,
		t.TRANSCHILDREFID,
		t.INVENTTRANSORIGIN,
		t.COSTAMOUNTPOSTED,
		o.REFERENCECATEGORY,
		d.INVENTLOCATIONID,
		ROUND((t.COSTAMOUNTPOSTED / t.QTY),2) AS 'LandedCost',
		CONVERT(date, t.DATEFINANCIAL) AS MaxLandedCostDate

/*THE FOLLOWING SUBQUERY GETS RID OF LINGERING DUPLICATE VALUES ON ITEMID*/

FROM (
	
	SELECT
		
		t.ITEMID,
		t.QTY,
		t.INVENTDIMID,
		t.TRANSCHILDREFID,
		t.INVENTTRANSORIGIN,
		t.COSTAMOUNTPOSTED,
		t.DATEFINANCIAL,
		ROW_NUMBER() OVER (PARTITION BY t.ITEMID ORDER BY t.DATEFINANCIAL DESC) AS tt 
		
	FROM InventTrans t
		
	LEFT JOIN InventTransOrigin o ON t.INVENTTRANSORIGIN = o.RECID

	LEFT JOIN InventDim d ON t.INVENTDIMID = d.INVENTDIMID
		
	WHERE o.REFERENCECATEGORY = '3' AND t.QTY > 0 AND t.COSTAMOUNTPOSTED > 0 AND (d.INVENTLOCATIONID = 'CPW01Q' OR d.INVENTLOCATIONID = 'DAL01' OR d.INVENTLOCATIONID = 'DAL01Q' OR d.INVENTLOCATIONID = 'KID01' OR d.INVENTLOCATIONID = 'KID01Q' /*AND t.DATEFINANCIAL <> '1900-01-01 00:00:00.000'*/)

	) t

LEFT JOIN InventTransOrigin o ON t.INVENTTRANSORIGIN = o.RECID

LEFT JOIN InventDim d ON t.INVENTDIMID = d.INVENTDIMID
	
WHERE tt = 1

ORDER BY t.ITEMID ASC, MaxLandedCostDate DESC