SELECT

	c.SALESID,
	c.INVOICEACCOUNT,
	MAX(c.INVOICEID) AS InvoiceID,
	--c.INVOICEID,
	s.CREATEDDATETIMELOCAL,
	c.DELIVERYNAME,
	m.MARKUPCODE AS 'Markup',
	m.VALUE AS 'MarkupCharge',
	p.SHIPPINGCHARGE AS 'CarrierShippingCharges',
	p.HANDLINGCHARGE AS 'CarrierHandlingCharges',
	p.OTHERCHARGE AS 'CarrierChargesOther',
	p.FUELSURCHARGE AS 'CarrierFuelCharges'

FROM CUSTINVOICEJOUR c

JOIN SalesLine s ON c.SALESID = s.SALESID

JOIN MARKUPTRANS m ON c.RECID = m.TRANSRECID

JOIN ShipCarrierPackage p ON c.SALESID = p.SALESID

WHERE m.TRANSTABLEID = '62' AND (m.MARKUPCODE LIKE '%Freight%' OR m.MARKUPCODE LIKE '%Delivery%' OR m.MARKUPCODE LIKE '%Rush%' OR m.MARKUPCODE LIKE '%Handling%')

GROUP BY c.SALESID, c.INVOICEACCOUNT, c.DELIVERYNAME, c.DELIVERYPOSTALADDRESS, m.MARKUPCODE, m.VALUE, s.CREATEDDATETIMELOCAL, p.SHIPPINGCHARGE, p.HANDLINGCHARGE, p.OTHERCHARGE, p.FUELSURCHARGE