--CREATE VIEW [SD_trade_agreements_UPC] AS

SELECT 

	p.RECID,
	p.ITEMRELATION AS ITEMID,
	i.NAMEALIAS AS NAMEALIAS,
	p.ACCOUNTRELATION AS PrimaryVendorId,
	c.EXTERNALITEMID AS ExternalID,
	b.ITEMBARCODE AS 'BarCode',
	--b.BARCODESETUPID AS 'BarCodeType',
	i.ITEMBUYERGROUPID AS Buyer,
	i.LHAPARENTSKU AS ParentSKU,
	REPLACE(REPLACE(REPLACE(i.OSSEXSTOCKFLAG,'1','Ex-stock'),'2','Ex-stock and Due In'),'0','None') AS 'Ex-stock',
	i.CITREQITEMWHSEID AS ManualCoverage,
	i.LHAMERCHDISCONID AS Discontinued,
	p.AMOUNT AS CurrentPurchasePrice,
	p.UNITID AS UNITID,
	MAX(COALESCE(NULLIF(p.FROMDATE,''), '1990-01-01 00:00:00.000')) AS FROMDATE/*,
	SUM(s.AVAILPHYSICAL) AS 'InventoryAvailable'*/

FROM  PriceDiscTable p

JOIN InventTable i ON p.ITEMRELATION = i.ITEMID

LEFT JOIN InventSum s ON p.ITEMRELATION = s.ITEMID

LEFT JOIN CustVendExternalItem c ON i.ITEMID = c.ITEMID AND i.PrimaryVendorId = c.CustVendRelation

JOIN InventItemBarCode b ON i.ITEMID = b.ITEMID

WHERE c.MODULETYPE = '3' AND  (b.BARCODESETUPID = 'UPCA' OR b.BARCODESETUPID = 'ISBN')

GROUP BY p.RECID, p.ITEMRELATION, i.NAMEALIAS, p.ACCOUNTRELATION, c.EXTERNALITEMID, b.ITEMBARCODE, b.BARCODESETUPID, i.ITEMBUYERGROUPID, i.LHAPARENTSKU, i.OSSEXSTOCKFLAG, i.CITREQITEMWHSEID, i.LHAMERCHDISCONID, p.AMOUNT, p.UNITID

--ORDER BY p.ITEMRELATION ASC